# Generated by Django 5.0.7 on 2024-07-20 06:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Укажите место выполнения привычки', max_length=100, verbose_name='Место выполнения привычки')),
                ('time', models.DateTimeField(help_text='Укажите дату и время выполнения привычки', verbose_name='Дата и время страта выполнения привычки')),
                ('action', models.CharField(help_text='Укажите действие, которое требуется сделать', max_length=200, verbose_name='Действие, которое требуется сделать')),
                ('pleasant_habit_sign', models.BooleanField(default=False, help_text='Укажите, является ли привычка приятной', verbose_name='Признак приятной привычки')),
                ('periodicity', models.SmallIntegerField(default=1, help_text='Укажите периодичность от 1 до 7, где 1 - один раз в неделю, а 7 - это каждый день.', verbose_name='Периодичность выполнения привычки')),
                ('reward', models.CharField(blank=True, help_text='Укажите награду за выполнение привычки', max_length=200, null=True, verbose_name='Награда за выполнение привычки')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), help_text='Укажите продолжительность выполнения привычки', verbose_name='Продолжительность выполнения привычки')),
                ('is_published', models.BooleanField(default=True, help_text='Укажите, опубликована ли привычка', verbose_name='Признак публичности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
