# Generated by Django 5.0.7 on 2024-07-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(help_text='Укажите дату и время выполнения привычки', verbose_name='Дата и время старта выполнения привычки'),
        ),
    ]
